<a href="https://colab.research.google.com/github/Rushikesh042/ML-DL-Algos/blob/main/AdaBoost.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import sklearn
from sklearn import datasets

In [2]:
# Loading and Visualizing the Dataset
iris = datasets.load_iris()
X = iris.data
Y = iris.target

In [3]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [4]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [5]:
iris.data[0:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [6]:
#Splitting the Dataset
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3)

In [7]:
#Building the AdaBoost Model
from sklearn.ensemble import AdaBoostClassifier 
adb = AdaBoostClassifier()
model = adb.fit(X_train, Y_train)
y_pred = model.predict(X_test)
y_pred

array([0, 1, 0, 0, 2, 0, 0, 2, 1, 2, 0, 2, 1, 2, 0, 0, 2, 0, 2, 1, 0, 1,
       1, 1, 0, 2, 0, 0, 2, 0, 1, 1, 1, 1, 0, 1, 2, 0, 2, 0, 2, 1, 1, 2,
       0])

In [8]:
#Evaluating the Model
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test, y_pred))
print(accuracy_score(Y_test, y_pred))

[[18  0  0]
 [ 0 14  3]
 [ 0  0 10]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        18
           1       1.00      0.82      0.90        17
           2       0.77      1.00      0.87        10

    accuracy                           0.93        45
   macro avg       0.92      0.94      0.92        45
weighted avg       0.95      0.93      0.93        45

0.9333333333333333


In [9]:
#Parameters Tuning:
"""Using SVM as a base estimator"""
from sklearn.svm import SVC
from sklearn.ensemble import AdaBoostClassifier 
svc = SVC(probability = True, kernel='linear')
adb = AdaBoostClassifier(n_estimators=100,base_estimator = svc, learning_rate= 0.01)

In [10]:
#Training and Predicting the AdaBoost Classifier
model = adb.fit(X_train, Y_train)
y_pred = model.predict(X_test)
y_pred

array([0, 1, 0, 0, 2, 0, 0, 2, 1, 2, 0, 2, 1, 2, 0, 0, 2, 0, 2, 2, 0, 1,
       1, 1, 0, 2, 0, 0, 2, 0, 1, 2, 1, 1, 0, 1, 2, 0, 2, 0, 2, 1, 1, 2,
       0])

In [11]:
#Evaluating the Model
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test, y_pred))
print(accuracy_score(Y_test, y_pred))

[[18  0  0]
 [ 0 12  5]
 [ 0  0 10]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        18
           1       1.00      0.71      0.83        17
           2       0.67      1.00      0.80        10

    accuracy                           0.89        45
   macro avg       0.89      0.90      0.88        45
weighted avg       0.93      0.89      0.89        45

0.8888888888888888
